### ISSUE TITLE
Droping decimal for dh11

### ISSUE THREAD

**Issue by jpajzinka** [danjperron/PicoDHT22#3]
Hi is there some reason to drop decimal part of temerature for DHT11? 

I modified the code to include it, and had parallel DHT11 and DHT22 connected,one next to the other, and then the temperature value was same.

https://github.com/danjperron/PicoDHT22/blob/b92d34f2fa9b3168cf32d42107c79a555a974fb6/DHT22.py#L163

**Comment by danjperron** [comment]
The DHT11  returns only integer.  The precision is ±2°C.

The DHT22 returns  one tenth of degree.  The precision is ±0.5°C.


DIsplay  decimal on the DHT11 isn't a true value.
